# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0412497f55c9ea7b1393798f26be42f94a5d7604dc015434d07291220dbbb897cfa5a342eebb99a17d1574df5e3125ae58296fe9a4ce40515f8df7a8f55ac3fa

test:
  secret_key_base: 27edbfa3dbe049e6cf9b188a8dbea35dabe19d100740be0245c2195f297d191532dc5bba83c15f0897b3282fc0a8e2d3d1a35c5a6d2968bf665b66c2345e86e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
